CREATE TABLE `post_installation_details` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `org_id` bigint(11) NOT NULL,
  `store_id` bigint(20) NOT NULL,
  `till_id` bigint(20) NOT NULL,
  `request` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `install_correctly` tinyint(1) NOT NULL,
  `device_image` blob NOT NULL,
  `device_color_request` tinyint(1) NOT NULL,
  `with_rf_switch` tinyint(1) NOT NULL,
  `with_network` tinyint(1) NOT NULL,
  `network_username` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `network_password` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `instore_version_update` tinyint(1) NOT NULL,
  `install_permission` tinyint(1) NOT NULL,
  `walkins__count_config` tinyint(1) NOT NULL,
  `damages_install` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `walkins_demo` tinyint(1) NOT NULL,
  `issues_install` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `mn_sy_count_record` tinyint(1) NOT NULL,
  `mn_count_process_explain` tinyint(1) NOT NULL,
  `visitor_staff_count_sync` tinyint(1) NOT NULL,
  `cap_escalation_matrix` tinyint(1) NOT NULL,
  `received_signed_copy` tinyint(1) NOT NULL,
  `signed_copy` blob NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `org_id`)
)
