CREATE TABLE `LOG_MERGE_USER` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ERROR_MESSAGE` text DEFAULT NULL,
  `FROM_USER_ID` int(11) NOT NULL,
  `MERGED_DATE` datetime NOT NULL,
  `NOTES` text NOT NULL,
  `ORG_ID` int(11) NOT NULL,
  `REQUEST_ID` varchar(100) NOT NULL,
  `STATUS` enum('SUCCESS','FAIL') NOT NULL,
  `TILL_ID` int(11) NOT NULL,
  `TO_USER_ID` int(11) NOT NULL,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `key_orgid` (`ORG_ID`)
)