CREATE TABLE `LOG_USER_REDEMPTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `API_RESPONSE_BODY` varchar(4096) DEFAULT NULL,
  `API_RESPONSE_HEADERS` json DEFAULT NULL,
  `GAME_ID` bigint(20) DEFAULT NULL,
  `BRAND_ID` bigint(20) DEFAULT NULL,
  `PLAY_TIME` datetime DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_gameId_userId` (`GAME_ID`,`USER_ID`),
  KEY `idx_userId` (`USER_ID`)
)