CREATE TABLE `REF_USER_GAME` (
  `ALLOWED_PLAY` int(11) NOT NULL,
  `EXHAUSTED_PLAY` int(11) NOT NULL,
  `GAME_ID` bigint(20) NOT NULL,
  `MAX_POSSIBLE_PLAY` int(11) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `ACTIVE` bit(1) DEFAULT 1,
  `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`GAME_ID`,`USER_ID`),
  KEY `idx_userId` (`USER_ID`),
  KEY `idx_created_on` (`CREATED_ON`),
  KEY `idx_gameId` (`GAME_ID`)
)