CREATE TABLE `REF_GAME_ITEM_METADATA_AUD` (
  `GAME_ITEM_ID` bigint(20) NOT NULL,
  `REV` int(11) NOT NULL,
  `REVTYPE` tinyint(4) DEFAULT NULL,
  `EXHAUSED_LIMIT` int(11) DEFAULT NULL,
  `MAX_LIMIT` int(11) DEFAULT NULL,
  `WIN_PERCENTAGE` double DEFAULT NULL,
  `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`GAME_ITEM_ID`,`REV`),
  KEY `idx_rev` (`REV`)
)