CREATE TABLE `TBL_GAME_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COLOR_CODE` varchar(255) DEFAULT NULL,
  `GAME_ID` bigint(20) NOT NULL,
  `REDEMPTION_ID` bigint(20) NOT NULL,
  `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_gameId` (`GAME_ID`),
  KEY `idx_RedemptionId` (`REDEMPTION_ID`)
)