CREATE TABLE `TBL_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IS_BLACKLISTED` bit(1) DEFAULT NULL,
  `BRAND_ID` bigint(20) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `EXTERNAL_ID` varchar(255) DEFAULT NULL,
  `MOBILE` bigint(20) DEFAULT NULL,
  `INTOUCH_USER_ID` bigint(20) DEFAULT NULL,
  `ACTIVE` bit(1) DEFAULT 1,
  `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_mobile_brandId` (`MOBILE`,`BRAND_ID`),
  KEY `idx_email_brandId` (`EMAIL`,`BRAND_ID`),
  KEY `idx_brandId_externalId` (`BRAND_ID`,`EXTERNAL_ID`),
  KEY `idx_intouchUserId_brandId` (`INTOUCH_USER_ID`,`BRAND_ID`)
)