CREATE TABLE `TBL_BRAND` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IS_ENABLED` bit(1) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `ORG_ID` bigint DEFAULT NULL,
  `TILL_CODE` varchar(255) DEFAULT NULL,
  `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_name` (`NAME`)
)