

CREATE TABLE `communication_details` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `message_queue_id` int(11) DEFAULT NULL,
  `message_id` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `org_id` int(11) unsigned NOT NULL,
  `bucket_id` int(11) DEFAULT NULL,
  `campaign_id` int(11) NOT NULL,
  `recipient_list_id` int(11) unsigned NOT NULL,
  `recipient_list_name` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_type` enum('GROUPED','TIMELINE','EXPIRY_REMINDER','SOCIAL','PROMOTION_EARNED','PROMOTION_EXPIRY', 'COMM_SERVICE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'GROUPED',
  `communication_type` enum('SMS','EMAIL','CALL_TASK','WECHAT','PUSH','ANDROID','IOS','FACEBOOK','GOOGLE','TWITTER','LINE','XENGAGE','NO_COMMUNICATION', 'VIBER', 'WHATSAPP', 'RCS') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sub_communication_type` enum('SMS','EMAIL','CALL_TASK','WECHAT','PUSH','ANDROID','IOS','FACEBOOK','GOOGLE','TWITTER','LINE','NONE','NO_COMMUNICATION', 'VIBER', 'FTP', 'WHATSAPP', 'RCS') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expected_delivery_count` int(11) unsigned NOT NULL,
  `overall_recipient_count` int(10) unsigned DEFAULT NULL,
  `subject` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `message_body` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority` int(11) NOT NULL,
  `state` enum('OPENED','PROCESSING','PAUSED','CLOSED','ERROR','REPLAY','REPLAYING','REPLAYED','RETRY') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OPENED',
  `is_legacy_table` tinyint(4) NOT NULL DEFAULT '0',
  `recieved_time` datetime NOT NULL,
  `picked_time` datetime NOT NULL,
  `resume_from_id` int(11) NOT NULL,
  `default_arguments` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `message_properties` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `queued_by` int(11) DEFAULT NULL,
  `last_updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`, `org_id`),
  KEY `campaign_id` (`org_id`,`campaign_id`),
  KEY `guid` (`guid`),
  KEY `org_campaign_message_idx` (`org_id`,`campaign_id`,`message_id`),
  KEY `idx_state` (`state`,`target_type`),
  KEY `idx_picked_time` (`picked_time`),
  KEY `org_msg_msgqueue_id` (`org_id`, `message_id`, `message_queue_id`),
  KEY `auto_update` (`last_updated_on`)
)
