

CREATE TABLE `coupon_upload` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `org_id` int(11) NOT NULL,
  `coupon_series_id` int(11) NOT NULL,
  `audience_id` int(11) DEFAULT '0',
  `audience_group_version_id` int(11) DEFAULT '0',
  `customer_type` enum('MOBILE','EMAIL','USER_ID','EXTERNAL_ID','NOT_TAGGED') COLLATE utf8mb4_unicode_ci DEFAULT 'MOBILE',
  `execution_status` enum('OPEN','PAUSE','RUNNING','COMPLETED','ERRED') COLLATE utf8mb4_unicode_ci DEFAULT 'OPEN',
  `status` enum('OPEN','AUDIENCE_INITIALIZER','TABLE_INITIALIZER','VALIDATION','PRE_COMMIT_PHASE','COMMIT_PHASE','POST_COMMIT_PHASE','NOTIFY') COLLATE utf8mb4_unicode_ci DEFAULT 'OPEN',
  `sub_status` enum('NONE','START','DONE') COLLATE utf8mb4_unicode_ci DEFAULT 'NONE',
  `total_upload_count` int(11) NOT NULL DEFAULT '0',
  `error_count` int(11) NOT NULL DEFAULT '0',
  `error_code` int(11) DEFAULT NULL,
  `error_message` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uploaded_file_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `error_file_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `success_file_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `temp_table_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_valid` tinyint(1) NOT NULL DEFAULT '1',
  `is_commit_enabled` tinyint(1) default '0',
  `current_issued_count` int(11) DEFAULT '0',
  `issuable_upload_count` int(11) DEFAULT '0',
  `upload_issued_count` int(11) DEFAULT '0',
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `uploaded_by` bigint(20) NOT NULL,
  `auto_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `uploaded_file_name` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`,`org_id`),
  KEY `org_id_coupon_series_id_execution_status_idx` (`org_id`,`coupon_series_id`, `execution_status`),
  KEY `execution_status_org_id_idx` (`execution_status`,`org_id`),
  KEY `auto_update_time_idx` (`auto_update_time`)
) ;
