CREATE TABLE `REF_REWARD_CATEGORY` (
 `CATEGORY_ID` bigint(20) NOT NULL,
 `REWARD_ID` bigint(20) NOT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`CATEGORY_ID`,`REWARD_ID`),
 KEY `idx_rewardId` (`REWARD_ID`),
 KEY `idx_categoryId` (`CATEGORY_ID`)
)