CREATE TABLE `TBL_VENDOR_REDEMPTION` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(255) DEFAULT NULL,
 `IS_ENABLED` bit(1) NOT NULL,
 `RESPONSE_KEYS` json DEFAULT NULL,
 `VENDOR_ID` bigint(20) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_vendorId` (`VENDOR_ID`)
)