CREATE TABLE `TBL_VENDOR_REDEMPTION_ACTION` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `API_BODY` json DEFAULT NULL,
 `API_HEADERS` json DEFAULT NULL,
 `API_TYPE` varchar(255) DEFAULT NULL,
 `API_URL` varchar(255) DEFAULT NULL,
 `CONTEXT_KEYS` json DEFAULT NULL,
 `IS_ENABLED` bit(1) DEFAULT NULL,
 `EXEC_ORDER` int(11) NOT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `IS_RETRY_ACTION` bit(1) DEFAULT NULL,
 `VENDOR_REDEMPTION_ID` bigint(20) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_vendorRedemptionId` (`VENDOR_REDEMPTION_ID`)
)