CREATE TABLE `TBL_COMMUNICATION` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `API_BODY` json DEFAULT NULL,
 `API_HEADERS` json NOT NULL,
 `API_TYPE` varchar(255) DEFAULT NULL,
 `API_URL` varchar(255) DEFAULT NULL,
 `BRAND_ID` bigint(20) DEFAULT NULL,
 `ORG_ID` bigint(20) DEFAULT NULL,
 `IS_ENABLED` bit(1) NOT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_brandId` (`BRAND_ID`),
 KEY `idx_orgId` (`ORG_ID`)
)