CREATE TABLE `TBL_LANGUAGE` (
 `CODE` varchar(255) NOT NULL,
 `IS_ENABLED` bit(1) DEFAULT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`CODE`)
)