CREATE TABLE `TBL_VENDOR` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `BRAND_ID` bigint(20) DEFAULT NULL,
 `ORG_ID` bigint(20) DEFAULT NULL,
 `IS_ENABLED` bit(1) DEFAULT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `IS_ENCRYPTIOM_REQUIRED` bit(1) DEFAULT NULL,
 `VENDOR_CLASS` varchar(255) DEFAULT NULL,
 `TYPE` enum('REWARDS','POINTS') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'REWARDS',
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_name_brandId` (`NAME`,`BRAND_ID`),
 KEY `idx_name_orgId` (`NAME`,`ORG_ID`),
 KEY `idx_id_brandId` (`ID`,`BRAND_ID`),
 KEY `idx_id_orgId` (`ID`,`ORG_ID`),
 UNIQUE KEY `UK_brandId_name` (`BRAND_ID`,`NAME`),
 UNIQUE KEY `UK_orgId_name` (`ORG_ID`,`NAME`)
)