CREATE TABLE `TBL_CITY` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `COUNTRY_ID` bigint(20) DEFAULT NULL,
 `IS_ENABLED` bit(1) DEFAULT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_countryId` (`COUNTRY_ID`),
 KEY `idx_name` (`NAME`)
)