CREATE TABLE `TBL_VENDOR_DETAILS` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(255) NOT NULL,
 `VALUE` varchar(255) NOT NULL,
 `VENDOR_ID` bigint(20) NOT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UK_vendorId_name` (`VENDOR_ID`,`NAME`)
)