CREATE TABLE `TBL_CATEGORY` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `BRAND_ID` bigint(20) DEFAULT NULL,
 `ORG_ID` bigint(20) DEFAULT NULL,
 `IS_ENABLED` bit(1) NOT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UK_brandId_name` (`BRAND_ID`,`NAME`),
 UNIQUE KEY `UK_orgId_name` (`ORG_ID`,`NAME`)
)