CREATE TABLE `TBL_AREA` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `CITY_ID` bigint(20) DEFAULT NULL,
 `IS_ENABLED` bit(1) NOT NULL,
 `NAME` varchar(255) NOT NULL,
 `LAST_UPDATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `CREATED_ON` timestamp DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`),
 KEY `idx_name` (`NAME`),
 KEY `idx_cityId` (`CITY_ID`)
)