CREATE TABLE `incremental-feature-generation` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `org_id` int(20) NOT NULL,
    `model` enum(
        'lapsation_propensity',
        'campaign_propensity',
        'segmented_popular',
        'bm25',
        'time_personalization_rule_based',
        'time_personalization_sequence_model',
        'repurchase_propensity',
        'category_sequence_predictor',
        'store_enrichment',
        'store_personalization',
        'implicit_als_buffalo',
        'time_personalization',
        'time_personalization_ensemble',
        'message_roi_prediction',
        'response_propensity',
        'transaction_propensity',
        'transaction_propensity_gbm',
        'customer_life_time_value_fact',
        'ramzan_transaction_propensity',
        'similar_items_attribute_based_fact',
        'frequently_bought_together_fact',
        'bought_together_also_bought_fact',
        'overall_popular_items_fact',
        'trending_items_fact',
        'upsell_propensity_fact',
        'cross_sell_propensity_fact',
        'promotional_product_propensity',
        'channel_propensity',
        'offer_propensity',
        'rfm_segmentation',
        'time_slot_propensity'
    ) NOT NULL,
    `algo` varchar(100) DEFAULT NULL,
    `snapshot_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `featuregen_start_date` timestamp NOT NULL,
    `featuregen_end_date` timestamp NOT NULL,
    `metadata` varchar(1000) NOT NULL,
    `attrib_json` varchar(1500) NOT NULL,
    `type` enum('incremental', 'full-run') NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB AUTO_INCREMENT = 1523 DEFAULT CHARSET = latin1;